# -*- coding: utf-8 -*-
"""NLP assignment .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_u-85y8TbGmWqZ38y-9u2H3K1I-q48YR
"""

import spacy
import random

nlp = spacy.load("en_core_web_sm")

def generate_mca_question(context):
    doc = nlp(context)
    sentence = random.choice(list(doc.sents))
    blank_word = random.choice([token for token in sentence if not token.is_punct])

    question_text = sentence.text.replace(blank_word.text, "______")
    correct_answers = [blank_word.text]

    other_options = [token.text for token in doc if token.is_alpha and token.text != correct_answers[0]]
    options = random.sample(other_options, 3) + correct_answers
    random.shuffle(options)

    question = {
        "question": question_text,
        "options": options,
        "correct_answers": correct_answers
    }

    return question

context = input("Enter the paragraph: ")
num_questions = int(input("Enter the number of questions: "))

for i in range(num_questions):
    question = generate_mca_question(context)
    print(f"Q{i+1}: {question['question']}")
    for j, option in enumerate(question['options'], 1):
        print(f"{j}. {option}")
    print(f"Correct Option: {question['correct_answers'][0]}\n")